services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always
    volumes:
      - redis_data:/data

  app:
    image: nextcloud:${NEXTCLOUD_TAG}
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      TZ: ${TZ}
      OVERWRITEPROTOCOL: https
      OVERWRITECLIURL: https://www.latercer.cloud
    volumes:
      - nextcloud_html:/var/www/html
      - nextcloud_data:/var/www/html/data

  cron:
    image: nextcloud:${NEXTCLOUD_TAG}
    restart: always
    depends_on:
      - app
    entrypoint: /cron.sh
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      TZ: ${TZ}
      OVERWRITEPROTOCOL: http
      OVERWRITECLIURL: http://localhost:8080
    volumes:
      - nextcloud_html:/var/www/html
      - nextcloud_data:/var/www/html/data

volumes:
  db_data:
  redis_data:
  nextcloud_html:
  nextcloud_data:
